import CAPICOM_STORE_LOCATION from '../capicom/CAPICOM_STORE_LOCATION';

/**
 * @category 4. Enums
 * @property {number} CAPICOM_LOCAL_MACHINE_STORE
 * @property {number} CAPICOM_CURRENT_USER_STORE
 * @property {number} CADESCOM_CONTAINER_STORE
 */
const CADESCOM_STORE_LOCATION = {
  CAPICOM_LOCAL_MACHINE_STORE:
    CAPICOM_STORE_LOCATION.CAPICOM_LOCAL_MACHINE_STORE,
  CAPICOM_CURRENT_USER_STORE: CAPICOM_STORE_LOCATION.CAPICOM_CURRENT_USER_STORE,
  CADESCOM_CONTAINER_STORE: 100,
};

export default CADESCOM_STORE_LOCATION;
